language: python
python:
- "3.5"
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
     packages:
     - python3-pip
     - python3-setuptools
     - python3-wheel
     - curl
     - net-tools
before_script:
- cp app.py test/app.py
- sudo bash -x scripts/provision.sh
script:
- sudo bash -x test/tests.sh
- /usr/bin/pytest test/test_app.py
